Addition to Authorization Server Setup page
AMWA-TV/nmos-authorization-implementation-guide pull request #54
Opened 2022-03-07 11:46 UTC by firthmj

Added comment on needed Keycloak configuration to resolve client IPs behind Apache Proxy

2022-03-09 11:04 UTC, firthmj commented
Additional commits to fork add clarifications to "Node to Authorization Server Interactions" page

2022-03-14 12:02 UTC, lo-simon requested changes

2022-03-14 12:02 UTC, lo-simon commented on docs/Node to Authorization Server Interactions.md
> +Details of the content of the `client_assertion` JWT can be found in [section 3 of RFC7523](https://tools.ietf.org/html/rfc7523#section-3). Note also, as mentioned in the [Authorization Server Setup
> In particular, the `iss` claim should also be the `client_id`,

The `iss` (issuer) claim should be the unique identifier for the Authorization Server that issued the JWT not the `client_id`, see https://datatracker.ietf.org/doc/html/rfc7523#section-3

2022-03-14 13:03 UTC, firthmj commented on docs/Node to Authorization Server Interactions.md
> +Details of the content of the `client_assertion` JWT can be found in [section 3 of RFC7523](https://tools.ietf.org/html/rfc7523#section-3). Note also, as mentioned in the [Authorization Server Setup
The JWT here is the self-signed one from the client to the authorization server. So the issuer is the client. Your link confirms that - the text is "a unique identifier for the entity that issued the JWT". RFC7523 is vague about exactly what the `iss` claim should be, beyond just a "unique identifier". But for an OpenID server, the documentation linked is explicit that it should be the `client_id`

2022-03-14 13:31 UTC, lo-simon commented on docs/Node to Authorization Server Interactions.md
> +Details of the content of the `client_assertion` JWT can be found in [section 3 of RFC7523](https://tools.ietf.org/html/rfc7523#section-3). Note also, as mentioned in the [Authorization Server Setup
You are right, the self-signed JWT `iss` should be the `cliend_id`

2022-03-14 13:33 UTC, lo-simon approved these changes
LGTM

2022-05-10 08:29 UTC, garethsb commented on docs/Node to Authorization Server Interactions.md
> +Details of the content of the `client_assertion` JWT can be found in [section 3 of RFC7523](https://tools.ietf.org/html/rfc7523#section-3). Note also, as mentioned in the [Authorization Server Setup
```suggestion
Details of the content of the `client_assertion` JWT can be found in [section 3 of RFC7523](https://tools.ietf.org/html/rfc7523#section-3). Note also, as mentioned in the [Authorization Server Setup page](Authorization%20Server%20Setup.md), that the Keycloak authentication server used as an example here is an OpenID Connect server, which places some additional restrictions on the JWT. In particular, the `iss` claim should also be the `client_id`, and the `jti` claim becomes mandatory. See the [OpenID Connect documentation on Client Authentication](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) for details and examples.
```

2022-05-10 08:29 UTC, garethsb approved these changes

2022-05-10 09:07 UTC, merged